config/routes.rb
Rails.application.routes.draw do
  resources :ambassadors

end

app/models/ambassador.rb
class Ambassador < ActiveRecord::Base
end

app/controllers/ambassadors_controller.rb
class AmbassadorsController < ApplicationController
  before_action :set_ambassador, only: [:show, :edit, :update, :destroy]

  # GET /ambassadors
  # GET /ambassadors.json
  def index
    @ambassadors = Ambassador.all
  end

  # GET /ambassadors/1
  # GET /ambassadors/1.json
  def show
  end

  # GET /ambassadors/new
  def new
    @ambassador = Ambassador.new
  end

  # GET /ambassadors/1/edit
  def edit
  end

  # POST /ambassadors
  # POST /ambassadors.json
  def create
    @ambassador = Ambassador.new(ambassador_params)

    respond_to do |format|
      if @ambassador.save
        format.html { redirect_to @ambassador, notice: 'Ambassador was successfully created.' }
        format.json { render :show, status: :created, location: @ambassador }
      else
        format.html { render :new }
        format.json { render json: @ambassador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ambassadors/1
  # PATCH/PUT /ambassadors/1.json
  def update
    respond_to do |format|
      if @ambassador.update(ambassador_params)
        format.html { redirect_to @ambassador, notice: 'Ambassador was successfully updated.' }
        format.json { render :show, status: :ok, location: @ambassador }
      else
        format.html { render :edit }
        format.json { render json: @ambassador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ambassadors/1
  # DELETE /ambassadors/1.json
  def destroy
    @ambassador.destroy
    respond_to do |format|
      format.html { redirect_to ambassadors_url, notice: 'Ambassador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ambassador
      @ambassador = Ambassador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ambassador_params
      params.require(:ambassador).permit(:first_name, :last_name, :email, :phone_number, :age, :school, :activities, :organizations, :spread_brand, :freedom_meaning, :hear_about, :address, :social_media, :ambassador_code)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/ambassadors_helper.rb
module AmbassadorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ambassadors/_form.html.erb
<%= form_for(@ambassador) do |f| %>
  <% if @ambassador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ambassador.errors.count, "error") %> prohibited this ambassador from being saved:</h2>

      <ul>
      <% @ambassador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.number_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :school %><br>
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :activities %><br>
    <%= f.text_field :activities %>
  </div>
  <div class="field">
    <%= f.label :organizations %><br>
    <%= f.text_field :organizations %>
  </div>
  <div class="field">
    <%= f.label :spread_brand %><br>
    <%= f.text_field :spread_brand %>
  </div>
  <div class="field">
    <%= f.label :freedom_meaning %><br>
    <%= f.text_field :freedom_meaning %>
  </div>
  <div class="field">
    <%= f.label :hear_about %><br>
    <%= f.text_field :hear_about %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :social_media %><br>
    <%= f.text_field :social_media %>
  </div>
  <div class="field">
    <%= f.label :ambassador_code %><br>
    <%= f.text_field :ambassador_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ambassadors/edit.html.erb
<h1>Editing ambassador</h1>

<%= render 'form' %>

<%= link_to 'Show', @ambassador %> |
<%= link_to 'Back', ambassadors_path %>

app/views/ambassadors/index.html.erb
<h1>Listing ambassadors</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Age</th>
      <th>School</th>
      <th>Activities</th>
      <th>Organizations</th>
      <th>Spread brand</th>
      <th>Freedom meaning</th>
      <th>Hear about</th>
      <th>Address</th>
      <th>Social media</th>
      <th>Ambassador code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ambassadors.each do |ambassador| %>
      <tr>
        <td><%= ambassador.first_name %></td>
        <td><%= ambassador.last_name %></td>
        <td><%= ambassador.email %></td>
        <td><%= ambassador.phone_number %></td>
        <td><%= ambassador.age %></td>
        <td><%= ambassador.school %></td>
        <td><%= ambassador.activities %></td>
        <td><%= ambassador.organizations %></td>
        <td><%= ambassador.spread_brand %></td>
        <td><%= ambassador.freedom_meaning %></td>
        <td><%= ambassador.hear_about %></td>
        <td><%= ambassador.address %></td>
        <td><%= ambassador.social_media %></td>
        <td><%= ambassador.ambassador_code %></td>
        <td><%= link_to 'Show', ambassador %></td>
        <td><%= link_to 'Edit', edit_ambassador_path(ambassador) %></td>
        <td><%= link_to 'Destroy', ambassador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ambassador', new_ambassador_path %>

app/views/ambassadors/new.html.erb
<h1>New ambassador</h1>

<%= render 'form' %>

<%= link_to 'Back', ambassadors_path %>

app/views/ambassadors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @ambassador.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @ambassador.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @ambassador.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @ambassador.phone_number %>
</p>

<p>
  <strong>Age:</strong>
  <%= @ambassador.age %>
</p>

<p>
  <strong>School:</strong>
  <%= @ambassador.school %>
</p>

<p>
  <strong>Activities:</strong>
  <%= @ambassador.activities %>
</p>

<p>
  <strong>Organizations:</strong>
  <%= @ambassador.organizations %>
</p>

<p>
  <strong>Spread brand:</strong>
  <%= @ambassador.spread_brand %>
</p>

<p>
  <strong>Freedom meaning:</strong>
  <%= @ambassador.freedom_meaning %>
</p>

<p>
  <strong>Hear about:</strong>
  <%= @ambassador.hear_about %>
</p>

<p>
  <strong>Address:</strong>
  <%= @ambassador.address %>
</p>

<p>
  <strong>Social media:</strong>
  <%= @ambassador.social_media %>
</p>

<p>
  <strong>Ambassador code:</strong>
  <%= @ambassador.ambassador_code %>
</p>

<%= link_to 'Edit', edit_ambassador_path(@ambassador) %> |
<%= link_to 'Back', ambassadors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrandAmb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>